apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: agent-server-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: agent-server
---
apiVersion: v1
kind: Service
metadata:
  name: agent-client-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: agent-client
  type: ClusterIP
